### ISSUE TITLE
Release 1.0 does not work on Ubuntu 22.04.1 LTS (cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by Enough7** [satviz/satviz#77]
Hi,

I followed the [Instructions]{https://github.com/satviz/satviz#installation} but when I run `./satviz` in directory `bin` I get the following error message:

```console
WARNING: Using incubator modules: jdk.incubator.foreign
Exception in Application start method
Exception in thread "Thread-0" java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/satviz-lib8459013318543043048.tmp: libsfml-window.so.2.5: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at edu.kit.satviz.consumer/edu.kit.satviz.consumer.bindings.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:32)
	at edu.kit.satviz.consumer/edu.kit.satviz.consumer.bindings.NativeObject.<clinit>(NativeObject.java:27)
	at edu.kit.satviz.consumer/edu.kit.satviz.consumer.config.Theme.<clinit>(Theme.java:34)
	at edu.kit.satviz.consumer/edu.kit.satviz.consumer.config.ConsumerConfig.<init>(ConsumerConfig.java:71)
	at edu.kit.satviz.consumer/edu.kit.satviz.consumer.gui.config.GeneralConfigController.<init>(GeneralConfigController.java:94)
	at edu.kit.satviz.consumer/edu.kit.satviz.consumer.gui.config.ConfigStarter.start(ConfigStarter.java:22)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:290)
	... 1 more
```
It says `cannot open shared object file: No such file or directory` am I missing a library?

**Comment by JohnnyJayJay** [comment]
Yes, you're missing a library - satviz currently doesn't include all of its dependencies statically. Try `sudo apt update` and `sudo apt install libsfml-dev libtheora-dev`.

**Comment by Enough7** [comment]
Thank you that works for me

**Comment by Enough7** [comment]
What is an external clause producer? I got [cadical](https://github.com/arminbiere/cadical) installed

**Comment by JohnnyJayJay** [comment]
An external clause producer is when you start the producer application separated from the consumer (visualisation) application.

E.g., you could run `satviz` somewhere and then connect to it from somewhere else by running `sat-prod ...`. If everything happens locally on your computer and you only require a basic setup, you probably want to use the embedded mode.

Note that you need to provide solvers as a dynamic library/shared object.

**Comment by Enough7** [comment]
I would like to run it locally just to learn from it. Can you recommend a SAT-Solver which supports being build as a shared object?
(I am not that familiar with C or C++ Builds)  I tried [cadical](https://github.com/arminbiere/cadical), [kissat](https://github.com/arminbiere/kissat) and [satch](https://github.com/arminbiere/satch) without success.

**Comment by JohnnyJayJay** [comment]
> (I am not that familiar with C or C++ Builds)  

You usually only need minimal knowledge to adjust the build settings to get shared objects (compiling with the `-fPIC` option and then packaging the object files). But if you don't want to deal with that for now, feel free to download the [cadical shared library](../blob/develop/satviz-producer/src/test/resources) used for testing in this repository.

**Comment by Enough7** [comment]
Thank you
